# Generated by Django 3.0.6 on 2020-08-31 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mess_id', models.CharField(max_length=11, unique=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('available', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('r', models.BooleanField(default=False)),
                ('i', models.BooleanField(default=False)),
                ('a', models.BooleanField(default=False)),
                ('d', models.BooleanField(default=False)),
                ('am', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Mess',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persons_per_room', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1)),
                ('expected_rent_per_person', models.DecimalField(decimal_places=2, max_digits=100)),
                ('expected_deposit_per_person', models.DecimalField(decimal_places=2, max_digits=100)),
                ('cupboard', models.BooleanField(default=False)),
                ('bedding', models.BooleanField(default=False)),
                ('ac', models.BooleanField(default=False)),
                ('tv', models.BooleanField(default=False)),
                ('geyser', models.BooleanField(default=False)),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='mess.Mess')),
            ],
        ),
        migrations.CreateModel(
            name='MessInWishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_type', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True)),
                ('booked', models.BooleanField(default=False)),
                ('booking_complete', models.BooleanField(default=False)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mess', to='mess.Mess')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='mess.Wishlist')),
            ],
        ),
        migrations.CreateModel(
            name='MessImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='mess/images/')),
                ('type', models.CharField(blank=True, choices=[('Kitchen', 'Kitchen'), ('Bedroom', 'Bedroom'), ('Dining', 'Dining'), ('Drawing', 'Drawing'), ('Hall', 'Hall'), ('Bathroom', 'Bathroom'), ('Balcony', 'Balcony'), ('Outside', 'Outside'), ('Other', 'Other')], max_length=20, null=True)),
                ('mess', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='mess.Mess')),
            ],
        ),
        migrations.CreateModel(
            name='MessDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_available_for', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Anyone')], max_length=1)),
                ('prefferable_guest', models.CharField(choices=[('W', 'Working Proffesional'), ('S', 'Student'), ('B', 'Both')], max_length=1)),
                ('available_from', models.DateField()),
                ('food_included', models.BooleanField(default=False)),
                ('no_smoking', models.BooleanField(default=False)),
                ('no_guardians_stay', models.BooleanField(default=False)),
                ('no_drinking', models.BooleanField(default=False)),
                ('no_girl_entry', models.BooleanField(default=False)),
                ('no_boys_entry', models.BooleanField(default=False)),
                ('no_non_veg', models.BooleanField(default=False)),
                ('gate_closing_time', models.TimeField()),
                ('description', models.TextField(blank=True, null=True)),
                ('mess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='mess.Mess')),
            ],
            options={
                'verbose_name_plural': 'Mess Details',
            },
        ),
        migrations.CreateModel(
            name='MessAmenities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundry', models.BooleanField(default=False)),
                ('room_cleaning', models.BooleanField(default=False)),
                ('warden_facility', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('cooking_allow', models.BooleanField(default=False)),
                ('power_backup', models.BooleanField(default=False)),
                ('parking_for_cycle', models.BooleanField(default=False)),
                ('parking_for_motor_bike', models.BooleanField(default=False)),
                ('parking_for_car', models.BooleanField(default=False)),
                ('mess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='amenities', to='mess.Mess')),
            ],
            options={
                'verbose_name_plural': 'Mess Amenities',
            },
        ),
        migrations.CreateModel(
            name='MessAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=10)),
                ('mess', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='mess.Mess')),
            ],
            options={
                'verbose_name_plural': 'Mess Address',
            },
        ),
    ]
