# Generated by Django 3.0.6 on 2020-09-05 20:03

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0002_messaddress_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messimage',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='mess/images/'),
        ),
        migrations.AlterField(
            model_name='messroom',
            name='expected_deposit_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=64),
        ),
        migrations.AlterField(
            model_name='messroom',
            name='expected_rent_per_person',
            field=models.DecimalField(decimal_places=2, max_digits=64),
        ),
    ]
