# Generated by Django 3.0.6 on 2020-09-06 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0003_auto_20200905_1503'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='requested',
            new_name='request',
        ),
    ]
