# Generated by Django 3.0.6 on 2020-09-27 06:16

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0004_auto_20200906_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messimage',
            name='image',
            field=models.ImageField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='mess/'),
        ),
    ]
