# Generated by Django 3.0.6 on 2020-10-31 13:58

from django.db import migrations, models
import mess.models


class Migration(migrations.Migration):

    dependencies = [
        ('mess', '0006_auto_20200927_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messimage',
            name='image',
            field=models.ImageField(storage=mess.models.GDStorage(), upload_to='mess'),
        ),
    ]
