# Generated by Django 3.0.6 on 2020-09-09 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Permission',
            field=models.ManyToManyField(to='auth.Permission'),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='auth.Group'),
        ),
    ]
