# Generated by Django 3.0.6 on 2020-09-09 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200910_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Permission',
            new_name='permission',
        ),
    ]
