# Generated by Django 3.0.6 on 2020-09-10 11:33

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200910_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.CharField(blank=True, choices=[('b', 'Buyer'), ('s', 'Seller')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='https://drive.google.com/uc?id=1IR5dx8piB72ZsKqhe1_YoU_FGkeTCFzO', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='account/'),
        ),
    ]
