# Generated by Django 3.0.6 on 2020-09-10 11:37

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200910_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='1IR5dx8piB72ZsKqhe1_YoU_FGkeTCFzO', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='account/'),
        ),
    ]
