# Generated by Django 3.0.6 on 2020-09-10 17:46

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200910_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', storage=gdstorage.storage.GoogleDriveStorage(), upload_to='account/'),
        ),
    ]
