# Generated by Django 3.0.6 on 2020-09-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('accounts', '0006_auto_20200910_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(blank=True, to='auth.Permission'),
        ),
    ]
