# Generated by Django 3.0.6 on 2020-10-31 13:58

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='default.png', storage=accounts.models.GDStorage(), upload_to='account/'),
        ),
    ]
