# Generated by Django 3.0.6 on 2021-05-03 05:05

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_id', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('available', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotel', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HotelAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('lon', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('street', models.CharField(max_length=50)),
                ('landmark', models.CharField(blank=True, max_length=100, null=True)),
                ('area', models.CharField(max_length=50)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(max_length=60)),
                ('zip_code', models.CharField(max_length=10)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='hotel.Hotel')),
            ],
            options={
                'verbose_name_plural': 'Hotel Address',
            },
        ),
    ]
